name: Compare Test Coverage
# This compares test coverage and throws an error if test coverage is lower than the previous run.

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  test-coverage:
    name: Compare Test Coverage
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - name: Checkout development branch
        uses: actions/checkout@v3
        with:
          ref: development

      - name: Setup Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: sudo apt-get install lcov

      - name: Get development branch coverage
        id: coverage-development
        run: |
          cd ./packages/contracts
          # generates lcov.info
          forge coverage --report lcov

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
        with:
          path-to-lcov: packages/contracts/lcov.info
          debug: true
