name: Yarn Audit

on:
  pull_request:
  push:

jobs:
  audit-and-fix:
    name: Audit & Fix
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.1.0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.14.1"

      - name: Debug
        run: yarn --version

      - name: Audit
        run: yes | npx yarn-audit-fix
